name: 'Create k3d cluster'
description: 'Action for creating single cluster'

inputs:
  restricted-registry-sa:
    description: 'Service Account (base64) with permissions to pull images from the restricted registry'
    required: false

runs:
  using: 'composite'
  steps:
    - name: Install k3d
      run: |
        curl -s https://raw.githubusercontent.com/k3d-io/k3d/v5.8.3/install.sh | bash
        k3d version
      shell: bash

    - name: Configure restricted registry access
      if: ${{ inputs.restricted-registry-sa }}
      run: |
        REGISTRIES_PATH=$(mktemp -d)/registries.yaml

        cat <<EOF >> ${REGISTRIES_PATH}
        mirrors:
          europe-docker.pkg.dev:
            endpoint:
              - https://europe-docker.pkg.dev/v2
        configs:
          europe-docker.pkg.dev:
            auth:
              username: _json_key_base64
              password: |
                ${{ inputs.restricted-registry-sa }}
        EOF

        echo "CUSTOM_FLAGS=${{ env.CUSTOM_FLAGS }} --registry-config ${REGISTRIES_PATH}" >> $GITHUB_ENV
        
      shell: bash

    - name: Create k3d cluster
      run: |
        k3d cluster create kyma \
          --agents 1 \
          --image rancher/k3s:v1.34.3-k3s1 \
          --port 80:80@loadbalancer \
          --port 443:443@loadbalancer \
          --k3s-arg "--flannel-backend=none@server:*" \
          --k3s-arg "--disable=traefik@server:0" ${{ env.CUSTOM_FLAGS }}
      shell: bash

    - name: Install Calico CNI
      run: |
        kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.31.3/manifests/operator-crds.yaml
        kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.31.3/manifests/tigera-operator.yaml
        kubectl create -f https://raw.githubusercontent.com/projectcalico/calico/v3.31.3/manifests/custom-resources.yaml
        # Wait until CoreDNS is ready
        kubectl rollout status -n kube-system deployment coredns
        # Patch the CNI config to make sure it is set up same as with the default Flannel backend
        kubectl patch installation default \
          --type=merge -p '{"spec":{"cni":{"binDir":"/var/lib/rancher/k3s/data/cni", "confDir":"/var/lib/rancher/k3s/agent/etc/cni/net.d"}}}'
      shell: bash
